In [1]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json
import gmaps
# Import API key
apikey = "AIzaSyBmYYlOthmdXZ341y_4r0seQlQ4z3C4AwU"

In [2]:
# Import cities file into the cities_pd DataFrame
cities_pd = pd.read_csv("../Resources/Cities.csv")
cities_pd.head()

            City         State
0  New York City      New York
1    Los Angeles    California
2        Chicago      Illinois
3        Houston         Texas
4   Philadelphia  Pennsylvania

In [4]:
# Add columns for lat, lng, airport name, airport address, airport rating.
# Hint: Be sure to specify "" as the initial value for each column.
base_url = "https://maps.googleapis.com/maps/api/geocode/json?"
#query_url = f'{base_url}address=Chicago&key={apikey}'

cities_pd['Lat']=""
cities_pd['Lng']=""
cities_pd['airport name']=""
cities_pd['airport address']=""
cities_pd['airport rating']=""
#print(query_url)
cities_pd.head()

,City,State,Lat,Lng,airport name,airport address,airport rating
0,New York City,New York,,,,,
1,Los Angeles,California,,,,,
2,Chicago,Illinois,,,,,
3,Houston,Texas,,,,,
4,Philadelphia,Pennsylvania,,,,,

In [6]:
# Loop through the cities_pd and get the lat/long for each city
# Hint: `requests.get(target_url).json()`
# Hint: `for index, row in cities_pd.iterrows():`
# Hint: `cities_pd.loc`
for index,row in cities_pd.iterrows():
    address = row["City"]
    query_url = f'{base_url}address={address}&key={apikey}'
    response = requests.get(query_url).json()
    row['Lat']=response['results'][0]["geometry"]["location"]["lat"]
    row['Lng']=response['results'][0]["geometry"]["location"]["lng"]

In [7]:
cities_pd.head()

,City,State,Lat,Lng,airport name,airport address,airport rating
0,New York City,New York,40.7128,-74.006,,,
1,Los Angeles,California,34.0522,-118.244,,,
2,Chicago,Illinois,41.8781,-87.6298,,,
3,Houston,Texas,29.7604,-95.3698,,,
4,Philadelphia,Pennsylvania,39.9526,-75.1652,,,

In [27]:
# Use the lat/lng we recovered to identify airports
# Hint: Code is similar to above block (i.e. you will need to use cities_pd.iterrows() again)
# Hint: Use the keyword search for "international+airport"
# Hint: Use a try-except to handle airports that are missing ratings
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
parameters = {"key":apikey,
              "radius":50000,
              "keyword":"international airport",
              }
for index,row in cities_pd.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    parameters["location"] = f"{lat},{lng}"
    response = requests.get(base_url, parameters).json()
    break
response

{'html_attributions': [],
 'results': [{'geometry': {'location': {'lat': 40.7285182, 'lng': -73.9592832},
    'viewport': {'northeast': {'lat': 40.72988037989272,
      'lng': -73.95781937010727},
     'southwest': {'lat': 40.72718072010728, 'lng': -73.96051902989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/airport-71.png',
   'id': '4fc4339c1f89db0c3f1632dcd793b7fb874264b0',
   'name': 'AirportLostandFound.com',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 250,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109813346821867978849/photos">AirportLostandFound.com</a>'],
     'photo_reference': 'CmRZAAAA4I-ZDMoSFFWXxYtyvV8u4_A82KOlA6VcU5frqxiVBVYVfV-XAkzkDZl_wKeYUIEA6-6J73HDPmFCo00XSUtrmiiUo9YDiCOneyChIWqqhxyj3leUY5myuGwno861_TCPEhBWqyIMyEf4ISzCURt39tw6GhQlLKJ_XDVyueSqy9y_atguco0COw',
     'width': 250}],
   'place_id': 'ChIJHX4Y2kFZwokRgd_rDbpu1iY',
   'plus_code': {'compound_code': 'P2HR+C7 Brooklyn, New York, United States',
    'global_code': '87G8P2HR+C7'},
   'rating': 4.4,
   'reference': 'ChIJHX4Y2kFZwokRgd_rDbpu1iY',
   'scope': 'GOOGLE',
   'types': ['airport', 'point_of_interest', 'establishment'],
   'user_ratings_total': 163,
   'vicinity': '67 West St, Brooklyn'},
  {'geometry': {'location': {'lat': 40.7425701, 'lng': -73.97194859999999},
    'viewport': {'northeast': {'lat': 40.74391992989271,
      'lng': -73.97059877010727},
     'southwest': {'lat': 40.74122027010727, 'lng': -73.97329842989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/airport-71.png',
   'id': 'df745369c079ee5f50c24881557e72f7057fb1eb',
   'name': 'TSS Heliport',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1253,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101530857509959540216/photos">lorraine torrella</a>'],
     'photo_reference': 'CmRaAAAAzomcR6g5biqlUmRYXL4Rab30SHrnoesNhqd7he7sHZ6CUpZRMI7zPTDLpnIx6GARwkFexA2KY0-jbgC8MZ6vWUi0EzMpM7c4Q4rUyGn3J5cdijmHFsbrcNrlM6Jhk5QnEhDH37vZu8NSVoqocPw_USayGhT4VhZSR3-bExFqfKSDVQV6Bij_CQ',
     'width': 923}],
   'place_id': 'ChIJewYoawZZwokRchDV_I0sNCQ',
   'plus_code': {'compound_code': 'P2VH+26 New York, United States',
    'global_code': '87G8P2VH+26'},
   'rating': 4.6,
   'reference': 'ChIJewYoawZZwokRchDV_I0sNCQ',
   'scope': 'GOOGLE',
   'types': ['airport', 'point_of_interest', 'establishment'],
   'user_ratings_total': 5,
   'vicinity': 'E 34th St, New York'}],
 'status': 'OK'}

In [25]:
response["results"][0]
# Save Data to csv


# Visualize to confirm airport data appears

{'geometry': {'location': {'lat': 40.6413111, 'lng': -73.77813909999999},
  'viewport': {'northeast': {'lat': 40.6635108, 'lng': -73.7634474},
   'southwest': {'lat': 40.63391119999999, 'lng': -73.82221419999999}}},
 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/airport-71.png',
 'id': '87586c86ef1c53323d31eba8260ca7f0ea7cb094',
 'name': 'John F. Kennedy International Airport',
 'photos': [{'height': 1840,
   'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101929585727476670441/photos">Martin Navratil</a>'],
   'photo_reference': 'CmRaAAAAGCH5CRBEGibDgXaoVtQ6g5iPAZ5eid9xNrA5v8k3pRp4kXf4-uLZOig3U4HshKOZzo9nzASbJzro1wtUCEBUO2cj1vvvVKQgyXV1Ib70tcK-5lTDgwCOl0nGY7hLR8D3EhBvP9N7lmzgOEi97S5bKV9xGhSZzHmolGtIaLmaMOvqnxy_cSEVTQ',
   'width': 3264}],
 'place_id': 'ChIJR0lA1VBmwokR8BGfSBOyT-w',
 'plus_code': {'compound_code': 'J6RC+GP New York, United States',
  'global_code': '87G8J6RC+GP'},
 'rating': 3.7,
 'reference': 'ChIJR0lA1VBmwokR8BGfSBOyT-w',
 'scope': 'GOOGLE',
 'types': ['airport', 'point_of_interest', 'establishment'],
 'user_ratings_total': 10546,
 'vicinity': 'Queens'}